# Generated by Django 2.2.24 on 2021-10-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='nombre',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
